### ISSUE TITLE
Kickstart

### ISSUE THREAD

**Issue by jas-** [RedHatSatellite/soe-ci#62]
I just came across your project and see that adding kickstart functionality is on the to do list.  I am the author of the [jaks](https://github.com/jas-/jaks) project that makes use of %pre and arguments passed to the kernel via the initramfs argument list to kickstart anaconda based distros. It also slipstreamed post configurations w/ %post.

It is all written in shell so it is portable. Is there a desired place to hook it in? I was looking at the kickstart script currently in place and it looks as if it is just picking up some recently modified .erb files vs. any type of os build.

I currently don't have an environment to facilitate testing and implementation but think it might be a good method of kickstart usage in your project.

**Comment by ericzolf** [comment]
Hi,
thanks for reaching out, nevertheless soe-ci is aimed at Satellite 6 / Foreman which has itself powerful handling of kickstarts via templates etc, so that I don't think that there would be a meaningful approach to integrate your project (soe-ci is mainly about feeding Sat6 with the kickstart kept in a Git-repo).
KR, Eric

**Comment by jas-** [comment]
No worries, just noticed it on your to do list
